CREATE TABLE taskTEST(
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo CHAR VARYING (255) NOT NULL,
    descripcion CHAR VARYING (255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_estimada TIMESTAMP DEFAULT NULL,
    finalizada TINYINT NOT NULL DEFAULT 0,
    estados ENUM('ON_TIME','LATE') NOT NULL
);